# Generated by Django 5.0.3 on 2024-04-03 20:44

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_messages", "0007_usergroup_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymmetricKey",
            fields=[
                ("pkid", models.BigAutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
                ),
                ("key", models.CharField(max_length=255, unique_for_year=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="custom_messages.messagegroup", to_field="id"
                    ),
                ),
            ],
            options={
                "ordering": ("-pkid",),
            },
        ),
    ]
