# Generated by Django 5.0.3 on 2024-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_messages", "0004_messagegroup_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="initialisation_vector",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
