# Generated by Django 5.0.3 on 2024-04-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
        ("custom_messages", "0007_usergroup_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="key",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="crypto.symmetrickey", to_field="id"
            ),
        ),
    ]
