export const signInRegisterText = {
    signIn: 'Sign in',
    email: 'Email address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    noAccountMade: `Don't yet have an account? Sign up`,
    forgotPassword: 'Forgot your password',
    enterName: 'Enter your name',
    firstName: 'First name',
    lastName: 'Surname',
    confirmYourPassword: 'Confirm your password',
    confirmPassword: 'Confirm password',
    register: 'Register',
    accountMade: 'Already have an account? Sign in',
    resetPassword: 'Reset password',
    resendEmail: 'Resend email',
    rememberDetails: 'Remember your account details? Log in',
    requestPasswordReset: 'Request a password reset',
    activateAndUnlockCapabilities: 'Click below to activate your account and unlock our full capabilities',
    alreadyActivated: 'Already activated? Continue to home',
    deleteAccount: 'Delete',
    save: 'Save',
    deletePermanently: 'Warning. This will permanently delete your account and all its data',
};

export const navigation = {
    logout: 'Logout',
    login: 'Login',
    home: 'Home',
    accounts: 'Accounts',
    partitions: 'Partitions',
    transactions: 'Transactions',
    account: 'Account',
    partition: 'Partition',
    transaction: 'Transaction',
    group: 'Group',
};
